itsdangerous.py

Because padding is only ever going to be added to the end.

Use rstrip instead of strip

---

itsdangerous.py

Pass `ensure_ascii=False` to `json.dumps`, this will produce shorter json dumps.

More compact JSON dumps for unicode strings

---

.travis.yml

'pypy3' on Travis passes all tests without modification.
Travis uses the following PyPy 3k version currently:
Python 3.2.5 (b2091e973da6, Oct 19 2014, 18:29:55)
[PyPy 2.4.0 with GCC 4.6.3]

Add PyPy 3 to travis build matrix

---

itsdangerous.py

https://github.com/pallets/itsdangerous/issues/46
1/1/2011 cutoff was removed, but comment was not updated.

Fix misleading EPOCH comment.

---

itsdangerous.py

Fixes #74.
The `JSONWebSignatureSerializer.load_payload` signature change is potentially breaking if anybody passed `return_header` as a second non-keyword argument to the method in the past. `itsdangerous.py` itself is using kwargs correctly everywhere so this shouldn't be an issue.
For the mixin, the change ensures it will pass additional arguments correctly.

Make `load_payload()` signature consistent between types

---

itsdangerous.py

Note that HMAC is still secure even with MD5. This is mostly a change for aesthetics so people will stop asking, although it doesn't hurt to be preemtive in this case.
Skipping SHA-256 for SHA-512 since it's more efficient on 64-bit.
See https://mail.python.org/pipermail/cryptography-dev/2017-March/000737.html for discussion.
#66, #77, #78

change default intermediate hash from SHA-1 to SHA-512

---

CHANGES

Hope this helps with cutting a new release.
We are currently using a fork at work since we need the fix for #89 in order to upgrade our codebase to Python 3. Would love to get rid of our fork.

Update changelog for 1.0

---

itsdangerous.py

Some dynamic value generators of API tools (for example Paw https://paw.cloud/extensions/JsonWebTokenDynamicValue) generate string value for timestamp and it raises the bad signature error.

Convert `exp` header to int if it is valid IntDate

---

CHANGES.rst
README.rst
docs/conf.py
docs/index.rst
setup.py
src/itsdangerous/serializer.py
src/itsdangerous/signer.py
src/itsdangerous/timed.py
tests/test_itsdangerous/test_serializer.py
tests/test_itsdangerous/test_timed.py

This rolls back the signing algorithm to HMAC-SHA1 by default and it
adds support for fallback signers.  This way a future version of itsdangerous
could rotate to a different algorithm without discarding everything else.
The fallbacks are just supported for the normal serializers.
Refs #112  #111

Added fallback signers and switch back to sha1

---

CHANGES.rst

Update changelog to present a technique for cross-version compatibilility in timestamp signers.

---

CHANGES.rst
src/itsdangerous/timed.py
tests/test_itsdangerous/test_timed.py

Fixes #126. This conditional checks that the age is not a future date.

Raise SignatureExpired error when age is in the future

---

CHANGES.rst
docs/serializer.rst
src/itsdangerous/__init__.py
src/itsdangerous/_json.py
src/itsdangerous/jws.py
src/itsdangerous/serializer.py

Removes simplejson in favor of Python's built-in json module. Since `itsdangerous.json` would just be an alias for that module now, it's replaced with an proxy that raises a deprecation warning on use.
closes #146

remove simplejson and deprecate itsdangerous.json

---

CHANGES.rst
src/itsdangerous/timed.py
tests/test_itsdangerous/test_timed.py

For timed serializers, a bad signature could result in `date_signed` being the raw int timestamp instead of a datetime. It is now consistently a datetime.
closes #124

date_signed is datetime not int

---

src/itsdangerous/jws.py
src/itsdangerous/serializer.py
src/itsdangerous/signer.py
tests/test_itsdangerous/test_jws.py
tests/test_itsdangerous/test_signer.py

This change is designed for https://github.com/pallets/flask/issues/1574
With this change, `Signer` and `Serializer` can accept a list of secret keys. For instance,
1. In 2019/09, we are using `a` as the secret key
2. In 2019/10, we are going to use `b` as the secret key
For 2019/09, we will use `Serializer(['a'])`, and later in 10, we will use `Serializer(['a', 'b'])`. Now the old dumped values can still be loaded, because `a` is in secret keys. But it will dump new value with secret key `b` in 2019/10.
Later, we can remove `a` from the secret keys, since it is not used anymore. Maybe in 2019/11.

Key rotate

---

CHANGES.rst
docs/concepts.rst
docs/index.rst
docs/license.rst
docs/serializer.rst
docs/signer.rst
docs/timed.rst
src/itsdangerous/serializer.py
src/itsdangerous/signer.py

Originally was only writing docs for key rotation (#141), but noticed there wasn't really a discussion on the general security concepts of the secret key, salt, etc.
This adds a new concepts page that discusses the secret key, salt, key rotation, and digest method, rather than having coverage spread out between signer and serializer pages and docstrings. Moves the docs on fallback signers to the serializer page instead of taking up half the docstring. Adds documentation for each signer and serializer parameter.
Also hit some other docs cleanup

create a new doc for general concepts

---

.github/workflows/tests.yaml
.gitignore
.pre-commit-config.yaml
CHANGES.rst
MANIFEST.in
docs/conf.py
requirements/dev.in
requirements/dev.txt
setup.cfg
src/itsdangerous/_json.py
src/itsdangerous/encoding.py
src/itsdangerous/exc.py
src/itsdangerous/serializer.py
src/itsdangerous/signer.py
src/itsdangerous/timed.py
src/itsdangerous/url_safe.py
tests/test_itsdangerous/test_jws.py
tests/test_itsdangerous/test_serializer.py
tests/test_itsdangerous/test_signer.py
tests/test_itsdangerous/test_timed.py
tests/test_itsdangerous/test_url_safe.py
tox.ini

Implementation notes:
* Didn't import types individually, used `import typing as _t` to shorten things.
* Common types are aliased in a `if TYPE_CHECKING:` block and referenced as string names.
* Only a few types (really just `str_bytes`) were common between modules, didn't bother with a common `_typing` module.
* All generics that aren't in the common block are strings to avoid runtime cost. This won't be necessary once we drop 3.6.
* The `return_timestamp` parameter of `TimestampSigner.unsign` changes the return type. To distinguish these, `@overload` is used, but because the method takes some other optional parameters, many overloads are needed to cover every combination. I added the overloads that matter, as mypy does use that to figure out a type elsewhere, but ignored the finding …

add typing with mypy

---

CHANGES.rst
src/itsdangerous/serializer.py
src/itsdangerous/signer.py

Was thinking of deprecating this, but the (deprecated) JWS subclasses used the same pattern of setting their default to `None` to get the parent's behavior, so I'll just leave it at that for now.
- fixes #237 
Checklist:

allow salt=None again

---

.github/workflows/tests.yaml
.pre-commit-config.yaml
CHANGES.rst
setup.cfg
tox.ini

[Python 3.6 is end-of-life on December 2021.](https://www.python.org/dev/peps/pep-0494/#lifespan)

drop Python 3.6

---

README.rst

Fixes a small typo in the Issue Tracker link in the README. I also dropped the trailing slash since it doesn't seem necessary.

Fix Issue Tracker link in README

---

CHANGES.rst
src/itsdangerous/timed.py
tests/test_itsdangerous/test_timed.py

Fixes unhandled `ValueError` when timestamp is too far in the future:
```
Traceback (most recent call last):
File "venv/lib/python3.8/site-packages/flask/app.py", line 2072, in wsgi_app
ctx.push()
File "venv/lib/python3.8/site-packages/flask/ctx.py", line 404, in push
self.session = session_interface.open_session(self.app, self.request)
File "venv/lib/python3.8/site-packages/flask/sessions.py", line 361, in open_session
data = s.loads(val, max_age=max_age)
File "venv/lib/python3.8/site-packages/itsdangerous/timed.py", line 203, in loads
base64d, timestamp = signer.unsign(
File "venv/lib/python3.8/site-packages/itsdangerous/timed.py", line 127, in unsign
ts_dt = self.timestamp_to_datetime(ts_int)
File "venv/lib/python3.8/site-packages/itsdangerous/timed.py", line 47, in …
```

Catch unhandled ValueError from future timestamp

---

src/itsdangerous/_json.py
src/itsdangerous/encoding.py
src/itsdangerous/exc.py
src/itsdangerous/serializer.py
src/itsdangerous/signer.py
src/itsdangerous/timed.py
src/itsdangerous/url_safe.py
tox.ini

* use deferred annotations, enabling modern syntax
* use `collections.abc`
* check with pyright
* verify exported API with `pyright --verifytypes`
* use specific ignores (for mypy)

improve typing

---

src/itsdangerous/serializer.py
src/itsdangerous/timed.py
src/itsdangerous/url_safe.py

`Serializer` now takes one generic parameter, either `str` or `bytes`, to define what `dumps` returns rather than a `str | bytes` union.
The `default_serializer` attribute and `serializer` argument are a generic protocol with the same parameter. The protocol requires an object that has a `loads` method and a `dumps` method that returns the appropriate type.
`URLSafeSerizlizer` is typed to always return `str`. This makes it more convenient as the user code no longer needs to do extra work to satisfy the type checker.
```python
s = URLSafeSerializer()
data = s.dumps(...)
```
fixes #347

type `Serializer` as generic

---

CHANGES.rst
src/itsdangerous/signer.py
tests/test_itsdangerous/test_serializer.py

`hashlib.sha1` may not be available in some FIPS builds that go beyond what FIPS requires into what it recommends. Apparently some RedHat containers do this. We don't want to change the default, but now it is accessed lazily so that it fails at runtime rather than at import time. This way, the developer has time after importing to change the default before using.
fixes #375

support FIPS builds without SHA-1

---

.github/workflows/tests.yaml
CHANGES.rst
pyproject.toml
src/itsdangerous/serializer.py
tests/test_itsdangerous/test_serializer.py
uv.lock

https://palletsprojects.com/versions
> When a release is made, it supports all Python versions that are not within six months of end of life (EOL). See [Python's EOL calendar](https://devguide.python.org/versions/) for timing.

drop end of life python versions
